(()=>{
  const p=(location.pathname.replace(/\/index\.html$/,'').replace(/\/$/,'')||'/');
  if(p!=='/admin')return;
  const main=document.querySelector('main#main'); if(!main)return;
  document.querySelector('.modern-newsletter')?.remove();
  const keyName='voigt-pta-admin-key';
  main.innerHTML=`<section class="admin-shell"><div class="container admin-login" id="adminRoot"><div class="admin-login-card"><span class="mini-label">PTA BOARD ACCESS</span><h1>Community dashboard</h1><p>Review volunteer interest, vendor applications, and newsletter subscribers.</p><form id="adminLogin"><label>Board member first name<input id="adminKey" type="password" autocomplete="current-password" autocapitalize="words" required placeholder="First name"></label><button class="btn primary" type="submit">Open dashboard</button></form><p class="admin-login-help">Current board members can sign in using their first name.</p><div id="adminStatus" class="newsletter-status"></div></div></div></section>`;
  const root=document.getElementById('adminRoot'),status=document.getElementById('adminStatus');
  async function load(key){status.textContent='Loading…';const r=await fetch('/api/admin',{headers:{'x-admin-key':key}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Could not load dashboard');sessionStorage.setItem(keyName,key);render(j,key);}
  function esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));}
  function render(data,key){const member=data.member||{};root.className='container admin-dashboard';root.innerHTML=`<div class="admin-welcome"><span class="mini-label">PTA BOARD DASHBOARD</span><h1>Welcome, ${esc(member.firstName||'Board Member')}.</h1><p>${esc(member.role||'PTA Board')} · <b>${data.volunteers.length}</b> volunteers · <b>${data.vendors.length}</b> vendors · <b>${data.newsletter.length}</b> subscribers</p><button class="btn secondary" id="adminLogout" type="button">Sign out</button></div><div class="admin-tabs"><button class="active" data-tab="volunteers">Volunteers</button><button data-tab="vendors">Vendors</button><button data-tab="newsletter">Newsletter</button></div><div id="adminTable"></div>`;
    const table=document.getElementById('adminTable');
    async function update(kind,id,status){const r=await fetch('/api/admin',{method:'PATCH',headers:{'Content-Type':'application/json','x-admin-key':key},body:JSON.stringify({kind,id,status})});if(!r.ok){const j=await r.json().catch(()=>({}));alert(j.error||'Could not update');}}
    function rows(kind){const arr=data[kind];if(kind==='newsletter'){table.innerHTML=`<div class="admin-grid">${arr.map(x=>`<div class="admin-row"><div><strong>${esc(x.email)}</strong><small>${new Date(x.created_at).toLocaleString()}</small></div><div>${esc(x.source||'')}</div><div></div><div></div><div></div></div>`).join('')||'<p>No subscribers yet.</p>'}</div>`;return;}
      table.innerHTML=`<div class="admin-grid">${arr.map(x=>`<div class="admin-row"><div><strong>${esc(kind==='vendors'?x.business_name:[x.first_name,x.last_name].filter(Boolean).join(' '))}</strong><small>${esc(x.email)}${x.phone?' · '+esc(x.phone):''}</small></div><div>${esc(kind==='vendors'?x.contact_name:x.event||'General availability')}</div><div><small>Submitted</small>${new Date(x.created_at).toLocaleDateString()}</div><div><select data-id="${x.id}"><option ${x.status==='new'?'selected':''}>new</option><option ${x.status==='reviewing'?'selected':''}>reviewing</option><option ${x.status==='approved'?'selected':''}>approved</option><option ${x.status==='contacted'?'selected':''}>contacted</option><option ${x.status==='closed'?'selected':''}>closed</option></select></div><button class="btn secondary" data-view="${x.id}">View</button><details style="grid-column:1/-1" id="detail-${x.id}"><summary>Details</summary><pre style="white-space:pre-wrap;font:12px/1.5 ui-monospace,monospace">${esc(JSON.stringify(x.payload,null,2))}</pre></details></div>`).join('')||'<p>No submissions yet.</p>'}</div>`;
      table.querySelectorAll('select[data-id]').forEach(sel=>sel.addEventListener('change',()=>{const id=Number(sel.dataset.id);const item=arr.find(v=>v.id===id);if(item)item.status=sel.value;update(kind,id,sel.value);}));table.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>document.getElementById(`detail-${b.dataset.view}`)?.toggleAttribute('open')));
    }
    rows('volunteers');root.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{root.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');rows(b.dataset.tab);}));
    document.getElementById('adminLogout')?.addEventListener('click',()=>{sessionStorage.removeItem(keyName);location.reload();});
  }
  document.getElementById('adminLogin').addEventListener('submit',e=>{e.preventDefault();load(document.getElementById('adminKey').value.trim()).catch(err=>status.textContent=err.message)});
  const saved=sessionStorage.getItem(keyName);if(saved)load(saved).catch(()=>sessionStorage.removeItem(keyName));
})();
