import { site, nav, events, festivalZones, stations, portalRoles } from '/src/data/site.js';

const app=document.getElementById('app');
const path=location.pathname.replace(/\/$/,'')||'/';
const titles={
'/':'Xenia Voigt Arts Academy PTA | Round Rock, TX','/about':'About | Xenia Voigt Arts Academy PTA','/join':'Membership | Xenia Voigt Arts Academy PTA','/volunteer':'Volunteer | Xenia Voigt Arts Academy PTA','/events':'Events | Xenia Voigt Arts Academy PTA','/viking-quest':'Viking Quest Fall Festival | Xenia Voigt Arts Academy PTA','/fundraising':'Support | Xenia Voigt Arts Academy PTA','/resources':'Resources | Xenia Voigt Arts Academy PTA','/contact':'Contact | Xenia Voigt Arts Academy PTA','/access':'Member Access | Xenia Voigt Arts Academy PTA'};
document.title=titles[path]||'Page Not Found | Xenia Voigt Arts Academy PTA';

const squiggle=()=>`<div class="squiggle" aria-hidden="true"><svg viewBox="0 0 100 20"><path d="M2 10 C12 1,22 19,34 10 S56 1,68 10 S88 1,98 10" fill="none" stroke="#c9a13a" stroke-width="2.4" stroke-linecap="round"/></svg></div>`;
const btn=(label,href,cls='primary')=>`<a class="btn ${cls}" href="${href}">${label}</a>`;

function header(){return `<div class="announce" id="announcement"><div class="announce-inner"><div><span class="star">★</span>Viking Quest Fall Festival · Friday, October 23 · 5:30–7:30 PM</div><button id="dismiss" aria-label="Dismiss announcement">×</button></div></div><header class="site-header"><div class="header-inner"><a class="brand" href="/"><div class="monogram">V</div><div><div class="brand-title">Xenia Voigt Arts<br class="desktop-br"> Academy</div><div class="brand-sub">PTA · ROUND ROCK, TX</div></div></a><nav class="nav" id="nav" aria-label="Primary navigation">${nav.map(([l,h])=>`<a href="${h}" class="${path===h?'active ':''}${h==='/viking-quest'?'featured':''}">${l}</a>`).join('')}<a href="/access" class="member-access ${path==='/access'?'active':''}">Sign in</a></nav><button class="hamburger" id="menu" aria-label="Open navigation menu" aria-expanded="false">☰</button></div></header>`}
function footer(){return `<footer class="footer"><div class="footer-inner"><div><h3>${site.name}</h3><small>${site.tagline}</small><small style="display:block;margin-top:14px">${site.affiliation}</small></div><div><b>Contact</b><p><a href="mailto:${site.email}">${site.email}</a></p><small>${site.address}</small></div><div><b>Explore</b><p><a href="/events">Events</a></p><p><a href="/join">Membership</a></p><p><a href="/access">Member Access</a></p></div></div><div class="footer-bottom">© 2026 Xenia Voigt Arts Academy PTA</div></footer>`}
function pageHero(title,subtitle,eyebrow='Xenia Voigt Arts Academy PTA'){return `<section class="page-hero"><div class="container"><div class="eyebrow">${eyebrow}</div><h1>${title}</h1>${squiggle()}<p>${subtitle}</p></div></section>`}
function section(title,body,alt=false,desc=''){return `<section class="section ${alt?'alt':''}"><div class="container"><div class="section-head"><div class="eyebrow">XENIA VOIGT ARTS ACADEMY PTA</div><h2>${title}</h2>${squiggle()}${desc?`<p>${desc}</p>`:''}</div>${body}</div></section>`}
function countdown(){return `<div class="countdown" data-countdown><div class="countbox"><b data-d>—</b><span>Days</span></div><div class="countbox"><b data-h>—</b><span>Hours</span></div><div class="countbox"><b data-m>—</b><span>Minutes</span></div><div class="countbox"><b data-s>—</b><span>Seconds</span></div></div>`}
function eventCard(e){return `<article class="card ${e.featured?'featured-card':''}"><span class="badge ${e.featured?'gold':'red'}">${e.featured?'Signature Event':'Upcoming'}</span><h3>${e.title}</h3><div class="meta"><span>${e.date}</span><span>${e.time}</span></div><p><b>${e.location}</b></p><p>${e.description}</p>${btn('View details',e.href,'outline')}</article>`}
function faq(items){return `<div class="faq">${items.map(([q,a],i)=>`<div class="faq-item"><button class="faq-q" aria-expanded="false" aria-controls="faq-${i}">${q}<span>+</span></button><div class="faq-a" id="faq-${i}" hidden>${a}</div></div>`).join('')}</div>`}

function home(){return `<main id="main"><section class="hero"><div class="container"><div class="eyebrow">Xenia Voigt Arts Academy PTA</div><h1>A more thoughtful kind of school community.</h1>${squiggle()}<p class="subhead">${site.tagline} We bring families, educators, and community partners together with warmth, intention, and care.</p><div class="buttons">${btn('Become a Member','/join')}${btn('Explore Events','/events','secondary')}${btn('Viking Quest','/viking-quest','featured')}</div></div></section>${section('What’s Happening',`<div class="grid two">${events.map(eventCard).join('')}<article class="card"><span class="badge red">PTA Calendar</span><h3>More 2026 dates are being confirmed</h3><p>We reviewed the current PTA Google Drive and are publishing only event dates that are confirmed in PTA records. Additional meetings, programs, and family events will appear here as dates are finalized.</p>${btn('See all events','/events','outline')}</article></div>`,false,'A curated view of confirmed PTA events and experiences.')}${section('Three Ways to Belong',`<div class="grid three"><article class="card"><h3>Join</h3><p>Membership is a simple way to support the school community. Volunteering is never required.</p>${btn('Membership','/join','outline')}</article><article class="card"><h3>Participate</h3><p>Give an hour, share a skill, or help at a signature event. Every contribution matters.</p>${btn('Volunteer','/volunteer','outline')}</article><article class="card"><h3>Partner</h3><p>Businesses and community organizations can support students through sponsorships, donations, and service.</p>${btn('Support PTA','/fundraising','outline')}</article></div>`,true)}${section('The Standard We Set',`<div class="grid two"><div class="card"><h3>Warm, organized, welcoming</h3><p>We want every family interaction with PTA to feel clear, considerate, and worth their time — from a first email to a campus-wide event.</p></div><div class="card"><h3>Student-centered by design</h3><p>PTA supports student activities, teacher and staff appreciation, family experiences, enrichment, and practical school needs.</p></div></div>`)}</main>`}
function about(){return `<main id="main">${pageHero('About the PTA','A volunteer-run local PTA focused on thoughtful service, strong relationships, and meaningful experiences for the Voigt community.')}${section('Who We Are',`<div class="grid two"><div class="card"><h3>Community, with purpose</h3><p>Parents and caregivers, teachers, staff, and community members working together to support Xenia Voigt Arts Academy in Round Rock.</p></div><div class="card"><h3>Our approach</h3><p>Welcoming, practical, inclusive, and organized. We aim to make participation easy and every experience feel considered.</p></div></div>`)}${section('What PTA Supports',`<div class="card"><ul class="list"><li>Student activities and enrichment</li><li>Teacher and staff appreciation</li><li>Family events and community-building</li><li>School needs and special projects</li><li>Volunteer and community partnerships</li></ul></div>`,true)}${section('Leadership',`<div class="grid three">${['President','Vice President','Secretary','Treasurer','Communications','Committee Leadership'].map(r=>`<div class="card"><h3>${r}</h3><p>Leadership information coming soon.</p></div>`).join('')}</div>`,false,'Current officer and committee information will be published after review.')}</main>`}
function join(){return `<main id="main">${pageHero('Membership','Belonging starts here. Join the PTA to support students, stay connected, and have a voice — with no volunteer requirement.')}${section('Why Join?',`<div class="grid two"><div class="card"><h3>Membership connects you</h3><ul class="list"><li>Support programs and family experiences</li><li>Stay close to PTA news and priorities</li><li>Have a voice in PTA</li><li>Strengthen the school community</li></ul></div><div class="card"><h3>Your time is still yours</h3><p>Joining the PTA does not require volunteering. Members participate at the level that works for their family.</p><p class="notice">Official Texas PTA membership link will be connected here after final review.</p></div></div>`)}${section('Membership FAQ',faq([['Do I have to volunteer to join?','No. PTA membership and volunteering are separate.'],['Who can join?','Parents, caregivers, teachers, staff, grandparents, and community supporters are welcome.'],['Can I be both a parent and a PTA member?','Absolutely. Your account can hold more than one role, so a parent who is also a PTA member will receive access appropriate to both.'],['How much does membership cost?','Membership dues will be shown with the official signup link.']]),true)}</main>`}
function volunteer(){return `<main id="main">${pageHero('Volunteer','Flexible, welcoming ways to contribute — from one hour at an event to ongoing committee work.')}${section('Ways to Help',`<div class="grid three"><div class="card"><h3>Family Events</h3><p>Welcome guests, help with activities, support setup, and make events run smoothly.</p></div><div class="card"><h3>Viking Quest</h3><p>Setup, stations, games, food court support, welcome/check-in, and clean-up opportunities.</p></div><div class="card"><h3>Student Volunteers</h3><p>Student groups may support art activities, face painting, games, check-in, and family-friendly activity stations.</p></div></div><p class="notice" style="margin-top:20px">Some roles may require school approval or adult supervision. Sign-up links will be posted as they are approved.</p>`)}</main>`}
function eventsPage(){return `<main id="main">${pageHero('Events','A refined, easy-to-follow calendar of confirmed PTA experiences for 2026.')}${section('Confirmed 2026 Events',`<div class="grid two">${events.map(eventCard).join('')}<div class="card"><span class="badge gray">Calendar note</span><h3>Additional dates coming soon</h3><p>The connected PTA Drive currently contains one confirmed 2026 event date suitable for public posting: Viking Quest Fall Festival. We will add meetings, spirit nights, family events, and other programs as dates are confirmed in PTA records.</p></div></div>`)}${section('Past Events',`<div class="card"><h3>Highlights archive</h3><p>Photos and recaps from past PTA experiences will be added here.</p></div>`,true)}</main>`}
function viking(){const outdoor=festivalZones.outdoor.map(z=>`<div class="card"><h3>${z}</h3><p>Details are being finalized.</p></div>`).join('');const indoor=festivalZones.indoor.map(z=>`<div class="card"><h3>${z}</h3><p>${z.startsWith('Gym')?'A planned quiet, low-stimulation space with reduced lighting and noise, comfortable seating, sensory-friendly activities, and room to take a break. Caregivers welcome.':'Details are being finalized.'}</p></div>`).join('');return `<main id="main"><section class="festival-hero"><div class="container"><div class="eyebrow">Signature Fall Experience</div><h1>Viking Quest Fall Festival</h1>${squiggle()}<p>${site.festival.date} · ${site.festival.time}</p><p>${site.address}</p><p>${site.festival.admission}</p>${countdown()}<div class="buttons">${btn('Volunteer','/volunteer')}${btn('Support the Festival','/fundraising','secondary')}</div></div></section>${section('Outdoor Experiences',`<div class="grid three">${outdoor}</div>`)}${section('Indoor Experiences',`<div class="grid two">${indoor}</div>`,true)}${section('Viking Quest',`<div class="grid three">${stations.map(([n,t,d])=>`<div class="card"><span class="badge gold">${n}</span><h3>${t}</h3><p>${d}</p></div>`).join('')}</div>`)}${section('Food & Entertainment',`<div class="grid three"><div class="card"><h3>KK BBQ Mexican Food Truck</h3><span class="badge red">Participating</span></div><div class="card"><h3>Kona Ice</h3><span class="badge red">On Schedule</span></div><div class="card"><h3>Coco’s Eats & Sweets / Vaughan’s</h3><span class="badge red">Confirmed</span></div></div><p style="text-align:center;margin-top:20px;color:var(--muted)">More announcements coming soon.</p>`,true)}${section('Festival FAQ',faq([['Is admission free?',site.festival.admission],['What time is the festival?',`${site.festival.date}, ${site.festival.time}.`],['Where should families park?','Parking and traffic details are being finalized.'],['Is the event sensory-friendly?','Yes. The gym is planned as the Sensory-Friendly Viking Retreat.'],['Can I volunteer?','Yes. Visit the Volunteer page; sign-up details are coming soon.'],['Can a business sponsor or donate?',`Yes. Visit Support or email ${site.email}.`]])}</main>`}
function fundraising(){return `<main id="main">${pageHero('Support the PTA','Community support lets PTA create meaningful experiences while preserving more resources for students and school needs.')}${section('Ways to Partner',`<div class="grid two"><div class="card"><h3>In-kind donations</h3><p>Goods and services that strengthen events and programs.</p></div><div class="card"><h3>Silent auction donations</h3><p>Experiences, gift cards, and family-focused contributions.</p></div><div class="card"><h3>Event sponsorship</h3><p>Support Viking Quest and future PTA experiences.</p></div><div class="card"><h3>Service partnerships</h3><p>Share time, expertise, or community resources.</p></div></div><div class="buttons">${btn('Contact PTA','/contact')}</div>`)}</main>`}
function resources(){return `<main id="main">${pageHero('Resources','A polished home for PTA information, forms, meeting materials, volunteer resources, and event documents.')}${section('Resource Library',`<div class="grid three">${['PTA documents','Meeting information','Volunteer resources','School resources','Event forms','Fall Festival resources'].map(x=>`<div class="card"><h3>${x}</h3><p>Links are being organized and will appear here as they are approved for public access.</p></div>`).join('')}</div>`)}</main>`}
function contact(){return `<main id="main">${pageHero('Contact','Questions, ideas, volunteer interest, and community partnership inquiries are always welcome.')}${section('Get in Touch',`<div class="grid two"><div><form class="form" id="contactForm"><div class="field"><label for="name">Name</label><input id="name" required></div><div class="field"><label for="email">Email</label><input id="email" type="email" required></div><div class="field"><label for="topic">Topic</label><select id="topic"><option>Membership</option><option>Volunteer</option><option>Events</option><option>Fall Festival</option><option>Sponsorship</option><option>General Question</option></select></div><div class="field"><label for="message">Message</label><textarea id="message" required></textarea></div><button class="btn primary" type="submit">Continue</button></form><p id="formNotice"></p></div><div class="card"><h3>PTA Contact</h3><p><a href="mailto:${site.email}">${site.email}</a></p><p>${site.address}</p><p class="notice">The website contact form is a preview for now. Until a secure form endpoint is connected, email is the reliable way to reach PTA.</p></div></div>`)}</main>`}
function access(){return `<main id="main">${pageHero('Member Access','One account, role-aware access. Parents who are also PTA members can hold both roles without creating duplicate accounts.','Private Access')}${section('Choose Your Access',`<div class="access-shell"><div class="access-panel"><div class="portal-grid">${portalRoles.map(r=>`<div class="portal-card"><span class="badge ${r.key==='leadership'?'gold':'red'}">${r.key==='parent'?'Family':r.key==='member'?'Member':'Authorized'}</span><h3>${r.title}</h3><p>${r.description}</p></div>`).join('')}</div><div class="buttons"><button class="btn primary" id="signInPreview">Sign in</button><button class="btn outline" id="signUpPreview">Create account</button></div><p class="notice" style="margin-top:24px"><b>Security note:</b> The portal interface is ready, but real authentication is not active yet. Before collecting passwords or member information, we will connect a secure identity provider and configure role-based access. No credentials are being stored by this preview.</p></div></div>`)}${section('How roles will work',`<div class="grid three"><div class="card"><h3>Parent / caregiver</h3><p>Family-facing forms, events, volunteer opportunities, and updates.</p></div><div class="card"><h3>PTA member</h3><p>Member resources in addition to family access. A parent can hold both roles.</p></div><div class="card"><h3>Leadership</h3><p>Restricted tools and internal resources only for specifically authorized PTA roles.</p></div></div>`,true)}</main>`}
function notFound(){return `<main id="main">${pageHero('Page not found','That page may have moved while the new PTA website is being built.')}<section class="section"><div class="container" style="text-align:center">${btn('Return Home','/')}</div></section></main>`}

const routes={'/':home,'/about':about,'/join':join,'/volunteer':volunteer,'/events':eventsPage,'/viking-quest':viking,'/fundraising':fundraising,'/resources':resources,'/contact':contact,'/access':access};
app.innerHTML=`<a class="skip-link" href="#main">Skip to content</a>${header()}${(routes[path]||notFound)()}${footer()}`;

const menu=document.getElementById('menu'), navEl=document.getElementById('nav');
if(menu&&navEl){menu.addEventListener('click',()=>{const open=navEl.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'×':'☰';});navEl.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>navEl.classList.remove('open')));}
const dismiss=document.getElementById('dismiss');if(dismiss){dismiss.addEventListener('click',()=>{document.getElementById('announcement')?.remove();sessionStorage.setItem('ptaAnnouncementDismissed','1');});if(sessionStorage.getItem('ptaAnnouncementDismissed'))document.getElementById('announcement')?.remove();}
document.querySelectorAll('.faq-q').forEach(q=>q.addEventListener('click',()=>{const panel=document.getElementById(q.getAttribute('aria-controls'));const open=q.getAttribute('aria-expanded')==='true';q.setAttribute('aria-expanded',String(!open));panel.hidden=open;q.querySelector('span').textContent=open?'+':'−';}));
function tick(){const target=new Date(site.festival.target).getTime(),now=Date.now(),diff=Math.max(0,target-now);document.querySelectorAll('[data-countdown]').forEach(el=>{if(target<=now){el.innerHTML='<strong>Viking Quest is here!</strong>';return;}const d=Math.floor(diff/86400000),h=Math.floor(diff/3600000)%24,m=Math.floor(diff/60000)%60,s=Math.floor(diff/1000)%60;el.querySelector('[data-d]').textContent=d;el.querySelector('[data-h]').textContent=String(h).padStart(2,'0');el.querySelector('[data-m]').textContent=String(m).padStart(2,'0');el.querySelector('[data-s]').textContent=String(s).padStart(2,'0');});}tick();setInterval(tick,1000);
const form=document.getElementById('contactForm');if(form)form.addEventListener('submit',e=>{e.preventDefault();document.getElementById('formNotice').innerHTML=`This form is not sending yet. Please email <a href="mailto:${site.email}">${site.email}</a>.`;});
['signInPreview','signUpPreview'].forEach(id=>document.getElementById(id)?.addEventListener('click',()=>alert('Secure account authentication is the next setup step. This preview does not collect or store passwords.')));