import { site, nav, events, festivalZones, stations } from '/src/data/site.js';

const app=document.getElementById('app');
const path=location.pathname.replace(/\/$/,'')||'/';
const titles={
'/':'Xenia Voigt Arts Academy PTA | Round Rock, TX','/about':'About PTA | Xenia Voigt Arts Academy PTA','/join':'Join PTA | Xenia Voigt Arts Academy PTA','/volunteer':'Volunteer | Xenia Voigt Arts Academy PTA','/events':'Events | Xenia Voigt Arts Academy PTA','/viking-quest':'Viking Quest Fall Festival — Friday, October 23, 2026','/fundraising':'Fundraising & Sponsors | Xenia Voigt Arts Academy PTA','/resources':'Resources | Xenia Voigt Arts Academy PTA','/contact':'Contact | Xenia Voigt Arts Academy PTA'};
document.title=titles[path]||'Page Not Found | Xenia Voigt Arts Academy PTA';

const squiggle=()=>`<div class="squiggle" aria-hidden="true"><svg viewBox="0 0 100 20"><path d="M2 10 C12 1, 22 19, 34 10 S56 1, 68 10 S88 1, 98 10" fill="none" stroke="#d7a116" stroke-width="2.4" stroke-linecap="round"/></svg></div>`;
const btn=(label,href,cls='primary')=>`<a class="btn ${cls}" href="${href}">${label}</a>`;
function header(){return `<div class="announce" id="announcement"><div class="announce-inner"><div><span class="star">★</span>Join us at Viking Quest Fall Festival — Friday, October 23, 2026, 5:30–7:30 PM</div><button id="dismiss" aria-label="Dismiss announcement">×</button></div></div><header class="site-header"><div class="header-inner"><a class="brand" href="/"><div class="monogram">V</div><div><div class="brand-title">Xenia Voigt Arts<br class="desktop-br"> Academy</div><div class="brand-sub">PTA · ROUND ROCK, TX</div></div></a><nav class="nav" id="nav" aria-label="Primary navigation">${nav.map(([l,h])=>`<a href="${h}" class="${path===h?'active ':''}${h==='/viking-quest'?'featured':''}">${h==='/viking-quest'?'★ ':''}${l}</a>`).join('')}</nav><button class="hamburger" id="menu" aria-label="Open navigation menu" aria-expanded="false">☰</button></div></header>`}
function footer(){return `<footer class="footer"><div class="footer-inner"><div><h3>${site.name}</h3><small>${site.tagline}</small><small style="margin-top:14px">${site.affiliation}</small></div><div><b>Contact</b><p><a href="mailto:${site.email}">${site.email}</a></p><small>${site.address}</small></div><div><b>Quick Links</b><p><a href="/join">Join PTA</a></p><p><a href="/volunteer">Volunteer</a></p><p><a href="/events">Events</a></p></div></div><div class="footer-bottom">© 2026 Xenia Voigt Arts Academy PTA</div></footer>`}
function pageHero(title,subtitle,eyebrow='Xenia Voigt Arts Academy PTA'){return `<section class="page-hero"><div class="container"><div class="eyebrow">${eyebrow}</div><h1>${title}</h1>${squiggle()}<p>${subtitle}</p></div></section>`}
function section(title,body,alt=false,desc=''){return `<section class="section ${alt?'alt':''}"><div class="container"><div class="section-head"><div class="eyebrow">XENIA VOIGT ARTS ACADEMY PTA</div><h2>${title}</h2>${squiggle()}${desc?`<p>${desc}</p>`:''}</div>${body}</div></section>`}
function countdown(dark=false){return `<div class="countdown" data-countdown><div class="countbox"><b data-d>—</b><span>Days</span></div><div class="countbox"><b data-h>—</b><span>Hours</span></div><div class="countbox"><b data-m>—</b><span>Minutes</span></div><div class="countbox"><b data-s>—</b><span>Seconds</span></div></div>`}
function eventCard(e){return `<article class="card"><span class="badge red">Upcoming</span><h3>${e.title}</h3><div class="meta"><span>${e.date}</span><span>${e.time}</span></div><p>${e.location}</p><p>${e.description}</p>${btn('View details',e.href,'outline')}</article>`}
function faq(items){return `<div class="faq">${items.map(([q,a],i)=>`<div class="faq-item"><button class="faq-q" aria-expanded="false" aria-controls="faq-${i}">${q}<span>+</span></button><div class="faq-a" id="faq-${i}" hidden>${a}</div></div>`).join('')}</div>`}

function home(){return `<main id="main"><section class="hero"><div class="container"><div class="eyebrow">Xenia Voigt Arts Academy PTA</div><h1>Xenia Voigt Arts<br>Academy PTA</h1>${squiggle()}<p class="subhead">${site.tagline}</p><div class="buttons">${btn('Join the PTA','/join')}${btn('Volunteer','/volunteer','secondary')}${btn('View Events','/events','secondary')}${btn('Viking Quest Fall Festival','/viking-quest','featured')}</div></div></section>${section("What's Happening at Voigt",`<div class="grid two">${events.map(eventCard).join('')}<article class="card festival-card"><span class="badge gold">Featured</span><h3>Viking Quest Fall Festival</h3><div class="meta"><span>${site.festival.date}</span><span>${site.festival.time}</span></div><p>${site.festival.admission}</p>${countdown(true)}${btn('Explore Viking Quest','/viking-quest')}</article></div>`,false,'The Fall Festival is the big one — and more events and announcements are on the way.')}${section('Ways to Get Involved',`<div class="grid three"><article class="card"><h3>Join PTA</h3><p>Become part of the community supporting students, teachers, and families.</p>${btn('Learn about membership','/join','outline')}</article><article class="card"><h3>Volunteer</h3><p>Help in ways that fit your schedule — one event or throughout the year.</p>${btn('Volunteer','/volunteer','outline')}</article><article class="card"><h3>Support / Sponsor</h3><p>Local businesses and community partners can help make programs possible.</p>${btn('Partner with PTA','/fundraising','outline')}</article></div>`,true)}${section('Why PTA Matters',`<div class="card"><p>PTA helps support student activities, teacher and staff appreciation, family events, enrichment opportunities, and practical school needs. Every family’s involvement — whether through membership, volunteering, sharing ideas, or simply showing up — strengthens the school community.</p></div>`)}</main>`}
function about(){return `<main id="main">${pageHero('About PTA','A volunteer-run local PTA bringing families, educators, staff, and community partners together for Voigt students.')}${section('Who We Are',`<div class="grid two"><div class="card"><h3>Community first</h3><p>We are parents and caregivers, teachers, staff, and community members working together to support Xenia Voigt Arts Academy in Round Rock, Texas.</p></div><div class="card"><h3>Our mission</h3><p>We aim to build a welcoming, practical, inclusive school community where families feel connected and students benefit from meaningful experiences.</p></div></div>`)}${section('What PTA Supports',`<div class="card"><ul class="list"><li>Student activities</li><li>Teacher and staff appreciation</li><li>Family events</li><li>Enrichment opportunities</li><li>School needs</li></ul></div>`,true)}${section('Current Officers & Board',`<div class="grid three">${['President','Vice President','Secretary','Treasurer','Board Member','Board Member'].map(r=>`<div class="card"><h3>${r}</h3><p>Position: To be updated</p><p>Name: To be updated</p></div>`).join('')}</div>`,false,'Officer and board member announcements coming soon.')}</main>`}
function join(){return `<main id="main">${pageHero('Join PTA','Membership is one of the simplest ways to support the Voigt school community — and joining does not require volunteering.')}${section('Why Join PTA?',`<div class="grid two"><div class="card"><h3>Membership connects you</h3><ul class="list"><li>Connect with the school community</li><li>Stay informed</li><li>Support programs and events</li><li>Have a voice in PTA</li></ul></div><div class="card"><h3>No volunteer requirement</h3><p>Joining the PTA does not require volunteering. Membership and volunteering are separate — participate at the level that works for your family.</p><span class="btn disabled" aria-disabled="true">Official membership signup link coming soon</span></div></div>`,false)}${section('Membership FAQ',faq([['Do I have to volunteer to join?','No. Joining PTA does not require volunteering.'],['Who can join?','Parents/caregivers, teachers, staff, and community supporters are welcome.'],['How much does membership cost?','To be confirmed — PTA dues are being finalized.'],['When can I join?','Membership details and the official signup link are coming soon.'],['Can grandparents or community supporters join?','Yes. Community supporters are welcome.']]),true)}</main>`}
function volunteer(){return `<main id="main">${pageHero('Volunteer','Flexible ways to help throughout the year — whether you have an hour, an evening, or a special skill to share.')}${section('Ways to Volunteer',`<div class="grid three"><div class="card"><h3>General PTA</h3><p>Help with family events, school activities, planning, communications, and other PTA needs.</p></div><div class="card"><h3>Fall Festival</h3><p>Opportunities include setup, Viking Quest stations, games, food court support, welcome/check-in, and clean-up.</p></div><div class="card"><h3>Student Volunteers</h3><p>Fall Festival outreach includes National Art Honor Society and student groups supporting face painting, art activities, carnival/game stations, welcome/check-in, and family-friendly activity stations.</p></div></div><p class="notice" style="margin-top:20px">Some volunteer roles may require school approval or adult supervision.</p><div class="buttons"><span class="btn disabled">Volunteer signup coming soon</span><span class="btn disabled">Student volunteer signup coming soon</span></div>`)}</main>`}
function eventsPage(){return `<main id="main">${pageHero('Events','Stay connected with upcoming PTA events and family activities at Voigt.')}${section('Upcoming Events',`<div class="grid two">${events.map(eventCard).join('')}</div>`)}${section('Past Events',`<div class="card"><h3>Photos and highlights</h3><p>Photos and highlights from past events will be shared here.</p></div>`,true)}</main>`}
function viking(){let outdoor=festivalZones.outdoor.map(z=>`<div class="card"><h3>${z}</h3><p>Details coming soon.</p></div>`).join('');let indoor=festivalZones.indoor.map(z=>`<div class="card"><h3>${z}</h3><p>${z.startsWith('Gym')?'A quiet, low-stimulation space in the gym with reduced lighting and noise, comfortable seating, sensory-friendly activities, and a calm area to take a break. Open for the duration of the festival for any guest who needs it. Caregivers welcome.':'Details coming soon.'}</p></div>`).join('');return `<main id="main"><section class="section" style="background:var(--red);color:#fff"><div class="container" style="text-align:center"><div class="eyebrow" style="color:#f7d37b">Xenia Voigt Arts Academy PTA</div><h1 style="font:700 clamp(48px,6vw,72px)/1 'Source Serif 4',serif;margin:18px 0">Viking Quest Fall Festival</h1>${squiggle()}<p style="font-size:20px">Friday, October 23, 2026 · 5:30–7:30 PM</p><p>${site.address}</p><p>${site.festival.admission}</p>${countdown(true)}<div class="buttons">${btn('Volunteer','/volunteer')}${btn('Become a Sponsor','/fundraising','secondary')}${btn('Festival Details','#festival-info','featured')}</div></div></section><div id="festival-info"></div>${section('Outdoor Festival Areas',`<div class="grid three">${outdoor}</div>`)}${section('Indoor Festival Areas',`<div class="grid two">${indoor}</div>`,true)}${section('Viking Quest Stations',`<div class="grid three">${stations.map(([n,t,d])=>`<div class="card"><span class="badge gold">${n}</span><h3>${t}</h3><p>${d}</p></div>`).join('')}</div>`)}${section('Food & Entertainment',`<div class="grid three"><div class="card"><h3>KK BBQ Mexican Food Truck</h3><span class="badge red">Participating</span></div><div class="card"><h3>Kona Ice</h3><span class="badge gold">Availability pending</span></div><div class="card"><h3>Coco's Eats & Sweets</h3><span class="badge gray">Interested</span></div></div><p style="text-align:center;margin-top:20px;color:var(--muted)">More food and entertainment announcements coming soon.</p>`,true)}${section('Sponsors & Community Partners',`<div class="grid three">${[1,2,3].map(()=>`<div class="card"><h3>Community Partner</h3><p>Partner announcements coming soon.</p></div>`).join('')}</div>`)}${section('Frequently Asked Questions',faq([['Is admission free?',"Admission and children's activities are planned to be free. Details coming soon."],['What time is the festival?','Friday, October 23, 2026, 5:30–7:30 PM.'],['Where should families park?','Details coming soon.'],['Is the event sensory-friendly?','Yes — the Gym will host the Sensory-Friendly Viking Retreat. Details coming soon.'],['Can I volunteer?','Yes — visit the Volunteer page; sign-up details coming soon.'],['Can a business sponsor or donate?',`Yes — visit the Fundraising & Sponsors page or email ${site.email}.`],['What happens if weather changes plans?',"Details coming soon — we'll share updates with families."]]),true)}</main>`}
function fundraising(){return `<main id="main">${pageHero('Fundraising & Sponsors','Community support helps PTA create meaningful experiences while directing more resources toward students and school needs.')}${section('Ways Businesses Can Support',`<div class="grid two"><div class="card"><h3>In-kind donations</h3><p>Goods or services that help reduce event and program costs.</p></div><div class="card"><h3>Silent auction donations</h3><p>Family experiences, gift cards, and other donated items.</p></div><div class="card"><h3>Event sponsorship</h3><p>Support Viking Quest Fall Festival and other PTA events. Details coming soon.</p></div><div class="card"><h3>Volunteer/service partnerships</h3><p>Community organizations can contribute time, expertise, and hands-on support.</p></div></div><div class="buttons">${btn('Contact PTA About Sponsorship','/contact')}</div><p style="text-align:center"><a href="mailto:${site.email}">${site.email}</a></p>`)}</main>`}
function resources(){return `<main id="main">${pageHero('Resources','A growing home for PTA documents, meeting information, volunteer resources, school links, and event materials.')}${section('Resource Library',`<div class="grid three">${['PTA documents','Meeting information','Volunteer resources','School resources','Event forms','Fall Festival resources'].map(x=>`<div class="card"><h3>${x}</h3><p>Links coming soon.</p></div>`).join('')}</div>`)}</main>`}
function contact(){return `<main id="main">${pageHero('Contact PTA','Questions, ideas, volunteer interest, and community partnership inquiries are always welcome.')}${section('Get in Touch',`<div class="grid two"><div><form class="form" id="contactForm"><div class="field"><label for="name">Name *</label><input id="name" required></div><div class="field"><label for="email">Email *</label><input id="email" type="email" required></div><div class="field"><label for="topic">Topic *</label><select id="topic" required><option value="">Choose a topic</option><option>Membership</option><option>Volunteer</option><option>Events</option><option>Fall Festival</option><option>Sponsorship</option><option>General Question</option></select></div><div class="field"><label for="message">Message *</label><textarea id="message" required></textarea></div><button class="btn primary" type="submit">Preview Message</button><div id="formNotice" class="notice" hidden></div></form></div><div class="card"><h3>PTA Contact</h3><p><a href="mailto:${site.email}">${site.email}</a></p><p>${site.address}</p><p>This form is a preview in v1 and does not send yet.</p></div></div>`)}</main>`}
function notFound(){return `<main id="main">${pageHero('Page Not Found','We couldn’t find that page, but you can get back to the PTA home page below.')}<div class="container" style="text-align:center;padding-bottom:70px">${btn('Back Home','/')}</div></main>`}
const routes={'/':home,'/about':about,'/join':join,'/volunteer':volunteer,'/events':eventsPage,'/viking-quest':viking,'/fundraising':fundraising,'/resources':resources,'/contact':contact};
app.innerHTML=header()+(routes[path]?routes[path]():notFound())+footer();

const saved=sessionStorage.getItem('ptaAnnDismissed');if(saved==='1')document.getElementById('announcement')?.remove();
document.getElementById('dismiss')?.addEventListener('click',()=>{sessionStorage.setItem('ptaAnnDismissed','1');document.getElementById('announcement')?.remove()});
const menu=document.getElementById('menu'),navEl=document.getElementById('nav');menu?.addEventListener('click',()=>{const o=navEl.classList.toggle('open');menu.setAttribute('aria-expanded',o);menu.textContent=o?'×':'☰'});
document.querySelectorAll('.faq-q').forEach(b=>b.addEventListener('click',()=>{const id=b.getAttribute('aria-controls');const panel=document.getElementById(id);const open=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',String(!open));panel.hidden=open;b.querySelector('span').textContent=open?'+':'−'}));
function tick(){const t=new Date(site.festival.target).getTime(),n=Date.now(),diff=t-n;document.querySelectorAll('[data-countdown]').forEach(el=>{if(diff<=0){el.innerHTML='<div class="countbox" style="grid-column:1/-1"><b>Viking Quest is here!</b></div>';return}const d=Math.floor(diff/86400000),h=Math.floor(diff/3600000)%24,m=Math.floor(diff/60000)%60,s=Math.floor(diff/1000)%60;el.querySelector('[data-d]').textContent=d;el.querySelector('[data-h]').textContent=h;el.querySelector('[data-m]').textContent=m;el.querySelector('[data-s]').textContent=s})}tick();setInterval(tick,1000);
document.getElementById('contactForm')?.addEventListener('submit',e=>{e.preventDefault();const topic=document.getElementById('topic').value;const notice=document.getElementById('formNotice');notice.hidden=false;notice.innerHTML=`This form is a preview and does not send yet. Please email <a href="mailto:${site.email}?subject=${encodeURIComponent(topic)}">${site.email}</a>.`;});
